[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.start]
cmd = "cd backend && python server.py"

[variables]
PYTHONUNBUFFERED = "1"