directories:
  output: release
  buildResources: public
productName: HEMS Ops Center
executableName: HEMS-Ops-Center
appId: com.hems.opscenter
copyright: Copyright Â© 2024 SRP Consulting Group, LLC.
files:
  - filter:
      - dist
      - dist-electron
      - package.json
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/logo-main.png
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  runAfterFinish: true
  installerIcon: public/logo-main.png
  uninstallerIcon: public/logo-main.png
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  category: public.app-category.utilities
  icon: public/logo-main.png
  hardenedRuntime: true
  gatekeeperAssess: false
dmg:
  title: Install HEMS Ops Center
  icon: public/logo-main.png
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
publish: null
electronVersion: 32.3.3
